version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - ~/.n8n:/home/node/.n8n
    command: >
      sh -c "
      npm install -g n8n-nodes-greyhound &&
      n8n start
      "
    restart: unless-stopped
